### ISSUE TITLE
Broken reference in OWASP Top 10 declaration

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-java-security#111]
## What is the full stack trace of any errors you encountered?

```
17:57:47 [ERROR] Recipe validation error in org.openrewrite.java.security.OwaspTopTen.recipeList[7] (in jar:file:/C:/Users/myuser/.m2/repository/org/openrewrite/recipe/rewrite-java-security/2.0.6/rewrite-java-security-2.0.6.jar!/META-INF/rewrite/owasp.yml): recipe 'org.openrewrite.java.security.OwaspA010' does not exist.
```

It's written A010 once, but A10 the second time in the YAML file.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes, should be simple.

**Comment by timtebeek** [comment]
Thanks for reporting the issue and the quick fix in
- #112
