### ISSUE TITLE
Owasp recipe refers to missing Spring recipe

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-java-security#127]
## What version of OpenRewrite are you using?

I am using

- rewrite-java-security 2.5.0

## What is the full stack trace of any errors you encountered?

```
[ERROR] Recipe validation error in org.openrewrite.java.security.OwaspA01.recipeList[3] (in jar:file:/C:/Users/foo/.m2/repository/org/openrewrite/recipe/rewrite-java-security/2.5.0/rewrite-java-security-2.5.0.jar!/META-INF/rewrite/owasp.yml): recipe 'org.openrewrite.java.security.spring.UnvalidatedRedirect' does not exist.
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Maybe. The new entry in the yaml was added in https://github.com/openrewrite/rewrite-java-security/commit/894f757b9e23eb0e0a50444cd13ed2874017409e. I believe there is no such recipe anywhere in this or other rewrite repos, so the line should probably just be deleted again. However, I haven't really checked all the commits before and after that one, so I might miss something.

**Comment by knutwannheden** [comment]
@Bananeweizen Thanks for reporting. I indeed don't think that was intentional. I've removed it from the list.
