### ISSUE TITLE
UseFilesCreateTempDirectory should remove should remove unnecessary`assert(true)` statement.

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-java-security#33]
### Problem
> UseFilesCreateTempDirectory should remove the unnecessary `assert(true)` statement.

### Example diff

```diff
     }
 
     private File createGitCommit(String jobName) throws IOException, InterruptedException {
-        File dir = File.createTempFile("jenkins","git");
-        dir.delete();//result !needed
-        assertTrue(dir.mkdir());
+        File dir = Files.createTempDirectory("jenkins" + "git").toFile();//result !needed
+        assertTrue(true);
 
         ProcessBuilder pb = new ProcessBuilder("git", "clone", gtGerrituser
                 + "@" + gtHostname + ":"
```

also present in: https://github.com/reactor/reactor-netty/blob/ff58ef3898c04b30c985333f4d7d5b9643eda4e4/reactor-netty-core/src/test/java/reactor/netty/ByteBufFluxTest.java#L140-L150

#### Recipes in example diff:
- org.openrewrite.java.security.UseFilesCreateTempDirectory

### References:
- Recipe ID: `nbvd6`
- Recipe Name: "Use Files#createTempDirectory"
- Repository: jenkinsci/acceptance-test-harness/master
- Created at Wed Jun 15 2022 06:58:04 GMT-0700 (Pacific Daylight Time)

**Comment by JLLeitschuh** [comment]
Resolved by:
https://github.com/openrewrite/rewrite-java-security/commit/27b5dc1322fdfb169d82ffa8b367b39bbd301179
