### ISSUE TITLE
Use Files#createTempDirectory, Remove unnecessary statements in the block when removing the guard from a return statement

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-java-security#34]
### Problem
`src/main/java/io/github/karlatemp/publicationsign/signerimpl/GpgSignerImpl.java`
> Remove unnecessary statements in the block when removing the guard from a return statement

### Expected behavior
> Describe what you expected to see.

### Example diff

```diff
 import java.io.InputStreamReader;
 import java.math.BigInteger;
 import java.nio.charset.StandardCharsets;
+import java.nio.file.Files;
 import java.security.MessageDigest;
 import java.util.*;
 
```

```diff
             if (mkdir1(tmp)) return tmp;
         }
 
-        tmp = File.createTempFile("psign", null);
-        tmp.delete();
-        if (tmp.mkdirs()) return tmp;
+        tmp = Files.createTempDirectory("psign" + null).toFile();
+        return tmp;
         if (tmp.isDirectory()) return tmp;
         throw new IllegalStateException("Failed to create a temp directory for ci");
     }
```

#### Recipes in example diff:
- org.openrewrite.java.security.UseFilesCreateTempDirectory

### References:
- Recipe ID: `4UJhS`
- Recipe Name: "Use Files#createTempDirectory"
- Repository: Karlatemp/PublicationSign/master
- Created at Wed Jun 15 2022 07:12:22 GMT-0700 (Pacific Daylight Time)

**Comment by JLLeitschuh** [comment]
The fix, for now, should simply to leave the if statement as the following:
```java
if (true) return tmp;
```

This is already an intermediate state our code ends up in, so we can just leave it in this state.

This fix should be targeted at `SimplifyConstantIfBranchExecution`
